import type { Metadata } from "next";
import { Chelsea_Market} from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const chelseaMarket = Chelsea_Market({
  weight: ['400', '400'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chelseaMarket.className}>
        {children}
      </body>
    </html>
  );
}
