import type { Metadata } from "next";
import { Chelsea_Market} from "next/font/google";
import "./globals.css";

interface RootLayoutProps {
  children: React.ReactNode; 
}

export const metadata: Metadata = {
  title: "Cash Tracker App",
  description: "Project generated by create next app - Adam Grodzki",
};

const chelseaMarket = Chelsea_Market({
  weight: ['400'],
  subsets: ['latin'],
});

const RootLayout: React.FC<RootLayoutProps> = ({children}) => (
  <html lang="en"> 
    <body className={chelseaMarket.className}> 
      {children} 
    </body>
  </html>
);
export default RootLayout;

